### ISSUE TITLE
Expense cannot post journal

### ISSUE THREAD

**Issue by kathawut** [OCA/hr-expense#106]
## Module
Employee Advance and Clearing

## Describe the bug
When I want to Post Journal of Employee Expense when I Click "Post Journal Entries" I got Error

`Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1396, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1384, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/tongthai/hr_expense_advance_clearing/models/hr_expense_sheet.py", line 94, in action_sheet_move_create
    res = super().action_sheet_move_create()
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_expense/models/hr_expense.py", line 906, in action_sheet_move_create
    res = expense_line_ids.action_move_create()
  File "/usr/lib/python3/dist-packages/odoo/addons/sale_expense/models/hr_expense.py", line 46, in action_move_create
    return super(Expense, self).action_move_create()
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_expense/models/hr_expense.py", line 510, in action_move_create
    move_line_values_by_expense = self._get_account_move_line_values()
  File "/mnt/extra-addons/tongthai/l10n_th_account_tax_expense/models/hr_expense.py", line 34, in _get_account_move_line_values
    move_line_values_by_expense = super()._get_account_move_line_values()
  File "/mnt/extra-addons/tongthai/hr_expense_advance_clearing/models/hr_expense.py", line 65, in _get_account_move_line_values
    emp_advance = self.env.ref("hr_expense_advance_clearing.product_emp_advance")
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 514, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1952, in xmlid_to_object
    raise ValueError('No record found for unique ID %s. It may have been deleted.' % (xmlid))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: No record found for unique ID hr_expense_advance_clearing.product_emp_advance. It may have been deleted.`

## To Reproduce
**Affected versions**: 14

**Expected behavior**
I want to Post Journal Entries.

**Comment by Saran440** [comment]
@kathawut
ValueError: No record found for unique ID hr_expense_advance_clearing.product_emp_advance. It may have been deleted.`

it mean your product `Employee Advance` disappear. please check your product
not error from module.

**Comment by kathawut** [comment]
How to add employee advance

**Comment by Saran440** [comment]
Maybe you upgrade module `hr_expense_advance_clearing` again.

**Comment by kathawut** [comment]
After upgrade
[image: Screen Shot 2565-05-05 at 14.16.08.png]

นายคธาวุฒิ คำปอ
email1: ***@***.***
email2: ***@***.***
